const departments = ["COMPUTER ENGINEERING", "ELECTRIC-ELECTRONIC ENGINEERING", "CHEMICAL ENGINEERING", "CIVIL ENGINEERING",
"MECHANICAL ENGINEERING", "MATERIAL SCIENCE AND ENGINEERING", "INDUSTRIAL ENGINEERING"]

module.exports = departments